[versions]
# Plugin
androidGradlePlugin = "8.1.1"
kotlinAndroid = "1.9.10"
ksp = "1.9.10-1.0.13"

coreKtx = "1.10.1"
lifecycleRuntimeKtx = "2.6.1"

# Compose
activityCompose = "1.7.2"
composeBom = "2023.08.00"
androidxLifecycle = "2.5.1"
runtimeTracing = "1.0.0-alpha01"
navigation = "2.7.1"

# Testing
junit = "4.13.2"
extJunit = "1.1.5"
espressoCore = "3.5.1"

# Http
retrofit = "2.9.0"
moshi = "1.15.0"
loggingInterceptor = "4.11.0"

#room
room = "2.5.2"

# Image Loader
coil = "2.4.0"

# Dependency Injection
dagger = "2.48"
appcompat = "1.6.1"
material = "1.9.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroid" }
android-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
activity-compose = { group = "androidx.activity", name = "activity-compose" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
material3 = { group = "androidx.compose.material3", name = "material3" }
material = { group = "androidx.compose.material", name = "material" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose" }
runtime-tracing = { module = "androidx.compose.runtime:runtime-tracing" }
material3WindowSizeClass = { module = "androidx.compose.material3:material3-window-size-class" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
navigation-runtime-ktx = { module = "androidx.navigation:navigation-runtime-ktx", version.ref = "navigation" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "extJunit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

# Http
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }

#room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# Image Loader
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

# Dependency Injection
dagger-android = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
androidx-room-common = { group = "androidx.room", name = "room-common", version = "2.5.2" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
com-google-android-material-material = { group = "com.google.android.material", name = "material", version.ref = "material" }